server:
  port: 8091

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/powerup
    username: root
    password: admin
  jpa:
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true

management:
  endpoints:
    web:
      exposure:
        include: "*"


microservice-user: "http://localhost:8090"